version: '3.1'

services:

    web:
        container_name: ${WEB_NAME}
        image: ${WEB_IMAGE}:${WEB_VERSION}
        build: build/web
        environment:
            WEB_DOCUMENT_ROOT: /var/www
            WEB_PHP_SOCKET: 0.0.0.0:9000
        volumes:
            - ./laravel:/var/www/project
            - ./web/vhosts/vhost.conf:/opt/docker/etc/httpd/vhost.conf:delegated
        working_dir: /var/www
        networks:
            - laravel-network
        expose:
            - "9000"
        ports:
            - "${HTTPS_PORT}:80"
            - "${HTTP_PORT}:443"

    sql:
        container_name: ${SQL_NAME}
        image: ${SQL_IMAGE}:${SQL_VERSION}
        build: build/sql
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./sql/database:/var/lib/mysql
        networks:
            - laravel-network
        ports:
            - "${SQL_PORT}:3306"


    laravel:
        container_name: ${LARAVEL_NAME}
        image: ${LARAVEL_IMAGE}:${LARAVEL_VERSION}
        build: build/laravel
        volumes:
            - ./laravel:/var/www/project
            - ./build/laravel/php.ini:/usr/local/etc/php/php.ini
        working_dir: /var/www/binance
        depends_on:
            - sql
            - web
        networks:
            - laravel-network
        expose:
            - "9000"
            - "1025"
        privileged: true
        cap_add:
            - SYS_ADMIN
            - DAC_READ_SEARCH


networks:
    laravel-network:
        driver: bridge
